<a href="https://colab.research.google.com/github/notorious0789/Study-of-Pandas-Library/blob/main/Practical_9_Study_of_Pandas_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 9
#Title: Study of Pandas Library
#17 Feb 2026
#Apoorba Chatterjee
#PRN: 25070123020
#ENTC A1

In [2]:
import pandas as pd

s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
# Create DataFrame
data={"Name":['Naman','Smriti','Prateek'],
      "Marks":[98,98,98]}

df=pd.DataFrame(data)
df

      Name  Marks
0    Naman     98
1   Smriti     98
2  Prateek     98

In [4]:
#df.head() is first 5 entries and df.tail() is last 5 entries

In [5]:
#Structure of DataFrame
df.shape

(3, 2)

In [6]:
df.ndim

2

In [7]:
df.size

6

In [8]:
#Display Column names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [9]:
#Check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [10]:
#Access Individual Column
df['Name']

0      Naman
1     Smriti
2    Prateek
Name: Name, dtype: object

In [11]:
df['Marks']

0    98
1    98
2    98
Name: Marks, dtype: int64

In [12]:
#Access specific row
df.loc[1]

Name     Smriti
Marks        98
Name: 1, dtype: object

In [13]:
#Add a new column
df['Grade']=['A','A','A']
df

      Name  Marks Grade
0    Naman     98     A
1   Smriti     98     A
2  Prateek     98     A

In [14]:
#Update Data in DataFrame
#Change marks of student
df.loc[0,'Marks']=100
df

      Name  Marks Grade
0    Naman    100     A
1   Smriti     98     A
2  Prateek     98     A

In [15]:
from numpy import True_
#Delete a column
df.drop('Grade',axis=1,inplace=True)
df

      Name  Marks
0    Naman    100
1   Smriti     98
2  Prateek     98

In [16]:
#Perform Basic Statistical Analysis
df['Marks'].mean()

np.float64(98.66666666666667)

In [17]:
df['Marks'].max()

100

In [18]:
df['Marks'].min()

98

In [19]:
#Apply Condition
df[df['Marks']>99]

    Name  Marks
0  Naman    100